controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - j2n6s300_joint_1
      - j2n6s300_joint_2
      - j2n6s300_joint_3
      - j2n6s300_joint_4
      - j2n6s300_joint_5
      - j2n6s300_joint_6
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - j2n6s300_joint_finger_1
      - j2n6s300_joint_finger_2
      - j2n6s300_joint_finger_3
initial:  # Define initial robot poses per group
  - group: arm
    pose: home
  - group: gripper
    pose: close